[project]
name = "training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.20"
dependencies = [
    "brevitas>=0.12.1",
    "matplotlib>=3.10.9",
    "onnx>=1.21.0",
    "onnxoptimizer>=0.4.2",
    "onnxscript>=0.7.0",
    "torch>= 1.12, <= 2.8",
    "torchvision>=0.23.0",
]